### PR TITLE
Fix imports

### PR DESCRIPTION
**Pull request by skupr-anaconda**
Fix `PILLOW VERSION` double quotes in `setup.py` for **python 3.7** and **python 3.8**.
I think it's a bug in the source code https://github.com/python-pillow/Pillow/blob/e42d8b089084dac7604be656bebed522363ffd86/setup.py#L849-L856

### CODE REVIEW

**Comment by skupr-anaconda** [comment]
I opened an issue https://github.com/python-pillow/Pillow/issues/6437

**Comment by skupr-anaconda** [comment]
> The win-64 CI fails here, what do the logs say?

`win-64` agent here isn't stable, right now I use another internal CI system and it succeeded.

Or can it be a `conda-build` or python `3.7.*/3.8.*` bug? Because the source code wasn't changed for a couple of years, and our last build for v9.0.1 was successful.

FYI, the maintainers' compiler is `MSVC 19.16.27035.0`, (runtime `MSVC\14.16.27023`), our is `vs2017_win-64: 19.16.27032.1-hb4161e2_3` (vs2015_runtime:  `14.27.29016-h5e58377_2`).

But python versions are different for py37: the maintainers use python **3.7.9** but we use **3.7.13**.

**Review by tobijk — APPROVED** [review]
LGTM

**Comment by skupr-anaconda** [comment]
The last version of `pillow` we built (v9.0.1, https://repo.anaconda.com/pkgs/main/win-64/pillow-9.0.1-py37hdc2b20a_0.tar.bz2) was built using `conda-build-3.21.7`, 
Looking at the `conda-build` changelog for [v3.21.9](https://github.com/conda/conda-build/releases/tag/3.21.9), it was noticed some changes to support the new `setuptools >=60.0`

I updated the recipe meta.yaml with:
```
    - setuptools <60  # [win and (py==37 or py==38)]
    - setuptools      # [not (win and (py==37 or py==38))]
```
And now it succeeded on `win` for **py37-py3**8, concourse pipeline https://concourse.build.corp.continuum.io/teams/main/pipelines/skupr-pillow-9.2.0_fix

**Review by pseudoyim — APPROVED** [review]
👍 Awesome! Thank you for [conferring with the upstream maintainers](https://github.com/python-pillow/Pillow/issues/6437) on this!

**Pull request merged**
